# Generated by Django 5.2.8 on 2025-11-27 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='id_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AddField(
            model_name='guests',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='id_pictures'),
        ),
    ]
