# Generated by Django 5.2.8 on 2025-11-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0005_alter_guest_options_alter_guest_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={},
        ),
        migrations.AlterModelManagers(
            name='guest',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='oib',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='password',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='guest',
            name='id_number',
            field=models.CharField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGuests.guest'),
        ),
    ]
