# Generated by Django 6.0.1 on 2026-01-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0007_contactmessage_room_remove_booking_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
