# Generated by Django 6.0.1 on 2026-01-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0008_rename_full_name_guest_first_name_remove_guest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='key_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
