# Generated by Django 6.0.1 on 2026-01-25 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0009_booking_key_given_booking_status'),
        ('AppStaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppStaff.room'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='booking',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGuests.guest'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
