# Generated by Django 6.0.1 on 2026-01-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0010_alter_booking_room_remove_booking_special_requests_and_more'),
        ('AppStaff', '0002_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppStaff.guest'),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
