# Generated by Django 6.0.1 on 2026-01-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0011_alter_booking_guest_delete_guest'),
        ('AppStaff', '0003_remove_room_room_number_room_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AppStaff.guest'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppStaff.room'),
        ),
    ]
