# Generated by Django 6.0.1 on 2026-01-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0012_alter_booking_guest_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
