# Generated by Django 6.0.1 on 2026-01-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0013_booking_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payed',
        ),
    ]
