# Generated by Django 6.0.1 on 2026-01-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0014_remove_booking_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
