# Generated by Django 6.0.1 on 2026-01-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0016_contactmessage_replied_alter_booking_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
