# Generated by Django 6.0.1 on 2026-01-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuests', '0017_contactmessage_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='key_given',
        ),
    ]
