# Generated by Django 6.0.1 on 2026-01-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(default='', max_length=50)),
                ('number_of_beds', models.IntegerField(default=1)),
                ('rooms_available', models.IntegerField(default=0)),
                ('price_per_night', models.FloatField(default=0.0)),
            ],
        ),
    ]
