# Generated by Django 6.0.1 on 2026-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStaff', '0002_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='room_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite')], default='STANDARD', max_length=20),
        ),
    ]
