# Generated by Django 6.0.1 on 2026-01-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStaff', '0003_remove_room_room_number_room_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_numbers',
        ),
        migrations.AddField(
            model_name='room',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='room_pictures/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite'), ('FAMILY', 'Family')], default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppStaff.room')),
            ],
        ),
    ]
