# Generated by Django 6.0.1 on 2026-01-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStaff', '0004_remove_room_room_numbers_room_pics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pics',
        ),
    ]
