# Generated by Django 6.0.1 on 2026-01-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStaff', '0005_remove_room_pics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key',
        ),
    ]
