# Generated by Django 6.0.1 on 2026-01-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStaff', '0006_delete_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='id_picture',
            new_name='id_back',
        ),
        migrations.AddField(
            model_name='guest',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='guest_id_pictures/'),
        ),
    ]
