# Generated by Django 6.0.1 on 2026-01-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStaff', '0007_rename_id_picture_guest_id_back_guest_id_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='room_picture',
            field=models.ImageField(blank=True, null=True, upload_to='room_pictures/'),
        ),
    ]
